# LGE_table_6
# Numerical example 1
# Goal: reproduce Table 6 (bond price vs volatility sigma_I = sigma_D),
# using coupon cashflows stored in coupon.rds (generated by Hull–White script)



# ---------------------------
# 1) Load packages
# ---------------------------

library(COVID19)      # COVID19 data hub package (NOT used in this script)
library(demodelr)     # epidemiological model helper package (NOT used here)
library(matrixStats)  # provides fast matrix ops like colDiffs()  (USED)
library(ggplot2)      # plotting (NOT used here)
library(forecast)     # time series tools (NOT used here)
library(tseries)      # time series tools (NOT used here)
library(RQuantLib)    # QuantLib interface (NOT used here)
library(quantmod)     # finance data tools (NOT used here)
library(dplyr)        # tidy data manipulation (NOT used here)
library(tidyverse)    # collection of tidy packages (NOT used here)
library(zoo)          # rollmean(), rollapply() (USED)
library(Sim.DiffProc) # snssde2d() stochastic simulation (USED)
library(rstudioapi)   # getActiveDocumentContext() (USED)
library(xtable)       # LaTeX table output (NOT used now)

# These were for formatting the table; only knitr is used below.
library(knitr)        # kable() table printing (USED)
library(kableExtra)   # NOT used in final output; can remove to avoid install issues



# ---------------------------
# 2) Clean the session
# ---------------------------

graphics.off()        # closes all open plotting devices
rm(list = ls())       # removes all objects from the current workspace



# ---------------------------
# 3) Set working directory to the folder of this script (RStudio)
# ---------------------------

my_d <- dirname(rstudioapi::getActiveDocumentContext()$path)  # folder containing this .R file
setwd(my_d)                                                # set working directory to that folder
# This matters because readRDS("coupon.rds") looks in the working directory.



# ---------------------------
# 4) Model / experiment settings (Table 6 sensitivity to volatility)
# ---------------------------

set.seed(12345)       # sets the random seed for reproducibility (BUT see note below)

Total_infected <- 833*10^6  # carrying capacity for infections KI (833 million)
Total_death    <- 0.4*10^6  # carrying capacity for deaths KD (0.4 million)
g_I <- 0.04                 # growth rate (used for BOTH I and D drifts)

sigma <- seq(0.02, 0.4, 0.02)
# sigma is a vector: 0.02, 0.04, 0.06, ..., 0.40
# each sigma[j] is used as the volatility for BOTH infection and death processes.

Bond_Price <- c()     # will store the computed bond price for each sigma
P_C <- c()            # will store P(C) = P(trigger) for each sigma



# ---------------------------
# 5) Loop over volatility levels
# ---------------------------

for (j in 1:length(sigma)) {
  
  print(paste0("Simulating Scenario ", j , " out of ", length(sigma)))
  # prints progress message for each sigma
  
  # Pandemic scenario parameters (fixed except sigma)
  y1_max <- Total_infected   # KI (infection carrying capacity)
  y2_max <- Total_death      # KD (death carrying capacity)
  
  y1_min <- 1                # I(0) initial infections
  y2_min <- 1                # D(0) initial deaths
  
  numsim <- 5000               # number of Monte Carlo sample paths (M)
  # NOTE: paper Table 6 uses 5000 paths; 50 is much noisier.
  
  n <- 1104                  # number of days from 2017-07-07 to 2020-07-15 (inclusive)
  theta_I <- 5000            # trigger threshold for 7-day avg infections
  theta_D <- 2500            # trigger threshold for 7-day avg deaths
  
  # Stochastic logistic parameters for infections
  s0_I <- sigma[j]           # sigma_I: volatility for infections (varied in loop)
  r0_I <- g_I                # g_I: drift/growth rate for infections
  K0_I <- y1_max             # KI
  x0_I <- y1_min             # initial I(0)
  
  # Stochastic logistic parameters for deaths
  s0_D <- sigma[j]           # sigma_D: volatility for deaths (same as sigma_I)
  r0_D <- g_I                # set g_D = g_I in this example
  K0_D <- y2_max             # KD
  x0_D <- y2_min             # initial D(0)
  
  dt  <- 1                   # time step = 1 day
  m   <- n                   # number of steps used in snssde2d()
  M   <- numsim              # number of simulated paths
  rho <- 0.5                 # correlation between Brownian motions for I and D
  
  
  
  # ---------------------------
  # 5.1) Define and run the 2D stochastic logistic simulation: 
  #              (I(t), D(t)) WITH CORRELATED BROWNIAN MOTIONS
  # ---------------------------
  # We model cumulative infections I(t) and cumulative deaths D(t) as TWO coupled
  # stochastic processes (a 2-dimensional SDE system).
  #
  # "2D" here means the state vector is:
  #    Z(t) = ( X(t), Y(t) ) = ( I(t), D(t) )
  #
  # Each component follows a stochastic logistic growth equation:
  #
  #   dI(t) = g_I * I(t) * (1 - I(t)/K_I) dt  +  sigma_I * I(t) * (1 - I(t)/K_I) dB_I(t)
  #   dD(t) = g_D * D(t) * (1 - D(t)/K_D) dt  +  sigma_D * D(t) * (1 - D(t)/K_D) dB_D(t)
  #
  # The logistic factor (1 - I/K_I) forces growth to slow as I approaches capacity K_I.
  # Same idea for D with capacity K_D.
  #
  # We also assume the Brownian motions are CORRELATED:
  #   Corr(dB_I, dB_D) = rho
  #
  # In Sim.DiffProc::snssde2d(), we specify this correlation via a 2x2 matrix Sigma.
  
  
  fun_st_logistic <- function(dt, m, rho, M) {
    
    #---------------------------
    # (A) Define DRIFT terms (deterministic part)
    # ---------------------------
    # In snssde2d(), the state variables are named:
    #   x = first component of the state vector (we interpret it as I(t))
    #   y = second component of the state vector (we interpret it as D(t))
    #
    # fx must be an expression of length 2:
    #   fx[[1]] = drift for x (I)
    #   fx[[2]] = drift for y (D)
    #
    # Here:
    #   drift_I(x) = r0_I * x * (1 - x/K0_I)
    #   drift_D(y) = r0_D * y * (1 - y/K0_D)
    #
    # Units:
    #   r0_I and r0_D are per-day growth rates if dt is in days.
    # ---------------------------
    fx <- expression(
      r0_I * x * (1 - x / K0_I),   # drift for infections I(t)
      r0_D * y * (1 - y / K0_D)    # drift for deaths D(t)
    )
    
    # ---------------------------
    # (B) Define DIFFUSION terms (random part / volatility loading)
    # ---------------------------
    # gx must also be an expression of length 2:
    #   gx[[1]] = diffusion coefficient multiplying dB_I(t)
    #   gx[[2]] = diffusion coefficient multiplying dB_D(t)
    #
    # We use multiplicative noise consistent with the paper:
    #   diffusion_I(x) = s0_I * x * (1 - x/K0_I)
    #   diffusion_D(y) = s0_D * y * (1 - y/K0_D)
    #
    # Interpretation:
    # - When x is small, diffusion is small (noise scales with level)
    # - When x approaches K0_I, (1 - x/K0_I) -> 0, diffusion shrinks again
    #   meaning the process stabilizes near capacity
    #
    # s0_I, s0_D control the magnitude of randomness.
    # ---------------------------
    gx <- expression(
      s0_I * x * (1 - x / K0_I),   # diffusion for infections
      s0_D * y * (1 - y / K0_D)    # diffusion for deaths
    )
    
    # ---------------------------
    # (C) Initial condition vector
    # ---------------------------
    # snssde2d expects x0 = c(x0, y0)
    # Here we interpret:
    #   x0_I = I(0)   initial cumulative infections
    #   x0_D = D(0)   initial cumulative deaths
    #
    # In your setup both start at 1.
    # ---------------------------
    x0 <- c(x0_I, x0_D)
    
    # ---------------------------
    # (D) Start time
    # ---------------------------
    # You simulate from t0 to t0 + N*Dt
    # ---------------------------
    t0 <- 0
    
    # ---------------------------
    # (E) Correlation structure between the Brownian motions
    # ---------------------------
    # Sigma is a 2x2 correlation matrix:
    #
    #   [ 1     rho ]
    #   [ rho   1   ]
    #
    # This means:
    #   Corr(dB_I, dB_D) = rho
    #
    # If rho > 0: infections and deaths tend to have shocks in the same direction.
    # If rho < 0: shocks tend to move opposite directions.
    # rho = 0: independent shocks.
    # ---------------------------
    Sigma <- matrix(c(1, rho,
                      rho, 1), nrow = 2, byrow = TRUE)
    
    # ---------------------------
    # (F) IMPORTANT: Random seed placement
    # ---------------------------
    # If you set.seed() here, inside the function, then every time you call this
    # function (for each sigma scenario), you will reuse the SAME random stream.
    #
    # That is sometimes intentional ("common random numbers") to reduce Monte Carlo
    # noise when comparing scenarios. But if you want truly independent randomness
    # across sigma levels, REMOVE set.seed() here and only set.seed() once at top.
    # ---------------------------
    set.seed(123)  # <-- remove this if you want independent randomness per sigma
    
    # ---------------------------
    # (G) Run the simulation using snssde2d()
    # ---------------------------
    # Arguments:
    #   N      = number of time steps
    #   M      = number of Monte Carlo paths
    #   x0     = initial values c(I(0), D(0))
    #   t0     = start time
    #   Dt     = time increment (dt)
    #   drift  = fx (2D drift expression)
    #   diffusion = gx (2D diffusion expression)
    #   corr   = Sigma (correlation matrix for Brownian motions)
    #
    # Output 'res' includes:
    #   res$X : simulated values of x(t) for all paths over time (I paths)
    #   res$Y : simulated values of y(t) for all paths over time (D paths)
    #
    # NOTE: snssde2d returns X,Y in a flattened structure; you reshape them later.
    # ---------------------------
    res <- snssde2d(
      N = m,
      M = M,
      x0 = x0,
      t0 = t0,
      Dt = dt,
      drift = fx,
      diffusion = gx,
      corr = Sigma
    )
    
    return(res)
  }
  
  # ---------------------------
  # CALL THE MODEL
  # ---------------------------
  res <- fun_st_logistic(dt, m, rho, M)
  
  # ---------------------------
  # RESHAPE OUTPUT INTO MATRICES: rows=time, cols=path
  # ---------------------------
  # res$X and res$Y are lists/vectors; unlist() flattens them, then matrix()
  # reshapes into [time x path] format.
  simulated_I <- matrix(unlist(res$X), ncol = numsim, byrow = FALSE)  # I(t) paths
  simulated_D <- matrix(unlist(res$Y), ncol = numsim, byrow = FALSE)  # D(t) paths
  
  
  
  # ---------------------------
  # 5.2) Convert cumulative paths -> daily increments -> 7-day rolling quantities
  # ---------------------------
  
  Increment_I <- colDiffs(simulated_I, lag = 1)  # I(t) - I(t-1) for each path
  Increment_I <- pmax(Increment_I, 0)            # clamp negatives to 0
  nn <- nrow(Increment_I)                        # number of rows (time steps)
  
  index <- 1:nn                                  # time index used for zoo
  
  # storage matrices for 7-day moving average and GR(t)
  sim_avg7_I <- matrix(ncol = numsim, nrow = length(7:nn))  # maI(t)
  sim_GR_I   <- matrix(ncol = numsim, nrow = length(7:nn))  # GR(t)
  
  for (i in 1:numsim) {
    
    obj1 <- zoo(Increment_I[, i], index)  # zoo series for one path
    
    seven_avg_I <- rollmean(obj1, 7, align = "right", fill = 0)           # 7-day mean
    seven_sd_I  <- rollapply(obj1, width = 7, FUN = sd, align = "right", fill = 0)  # 7-day sd
    
    # extract days 7..nn into numeric vectors
    y11 <- as.data.frame(seven_avg_I[7:nn])
    y11 <- y11[["seven_avg_I[7:nn]"]]
    sim_avg7_I[, i] <- y11
    
    y33 <- as.data.frame(seven_sd_I[7:nn])
    y33 <- y33[["seven_sd_I[7:nn]"]]
    
    # define GR(t) = maI(t) - 1.533 * sd(t)
    sim_GR_I[, i] <- (y11 - (1.533 * y33))
  }
  
  # Do the same for deaths (7-day moving average only)
  Increment_D <- colDiffs(simulated_D, lag = 1)
  Increment_D <- pmax(Increment_D, 0)
  
  sim_avg7_D <- matrix(ncol = numsim, nrow = length(7:nn))  # maD(t)
  
  for (i in 1:numsim) {
    obj1 <- zoo(Increment_D[, i], index)
    seven_avg_D <- rollmean(obj1, 7, align = "right", fill = 0)
    y22 <- as.data.frame(seven_avg_D[7:nn])
    y22 <- y22[["seven_avg_D[7:nn]"]]
    sim_avg7_D[, i] <- y22
  }
  
  
  
  # ---------------------------
  # 5.3) Trigger detection
  # Trigger if maI(t)>theta_I AND maD(t)>theta_D AND GR(t)>0 at same time t
  # ---------------------------
  
  trigger <- 0               # count how many paths trigger
  common_index <- c()        # which simulation paths triggered
  common_time  <- c()        # the first trigger time (in the 7-day-indexed time)
  
  for (i in 1:numsim) {
    
    set_I  <- which(sim_avg7_I[, i] > theta_I)  # days where infection MA exceeds threshold
    set_D  <- which(sim_avg7_D[, i] > theta_D)  # days where death MA exceeds threshold
    set_GR <- which(sim_GR_I[, i] > 0)          # days where GR > 0
    
    common <- Reduce(intersect, list(set_I, set_D, set_GR))  # times all 3 conditions are true
    
    if (length(common) > 0) {
      trigger <- trigger + 1
      common_index <- append(common_index, i)     # path i triggered
      common_time  <- append(common_time, common[1]) # first time trigger occurs
    }
    
    common <- NULL  # reset
  }
  
  
  
  # ---------------------------
  # 5.4) Price conditional on trigger time using coupon schedule (coupon.rds)
  # ---------------------------
  
  coupon_data <- readRDS(file = "coupon.rds")
  # coupon_data is expected to have columns: Time (days) and CF (cashflow)
  # and the last CF should include redemption.
  
  pv <- function(y, cf, t) sum(cf / (1 + y)^t)
  # present value of cashflows cf at times t (in years) under annual yield y
  
  y1 <- 0.08673402           # fixed required yield (8.673402%)
  
  BondValue_partial <- c()   # store PV of cashflows up to trigger time
  
  for (i in 1:length(common_index)) {
    
    trigger_time <- common_time[i] + 6
    # because your 7-day series starts at day 7 -> index 1,
    # so you add 6 to map back to original day count.
    
    coupondf <- subset(coupon_data, coupon_data$Time <= trigger_time)  # coupons paid up to trigger
    cf <- as.numeric(coupondf$CF)
    t  <- coupondf$Time / 360  # convert days to years using Actual/360
    
    presentV <- pv(y1, cf, t)  # PV of coupons received before trigger
    BondValue_partial <- append(BondValue_partial, presentV)
  }
  
  price1 <- mean(BondValue_partial)
  # E[BondPrice | Trigger]
  # NOTE: if no path triggers (BondValue_partial is empty), mean() returns NA.
  
  price2 <- 225
  # E[BondPrice | No Trigger] set to issue price / advertised price (USD 225M)
  
  
  
  # ---------------------------
  # 5.5) Combine using probabilities
  # ---------------------------
  
  prob1 <- 0.1393            # P(H): probability of pandemic during term
  prob2 <- (trigger / numsim) # P(C|H): trigger probability conditional on pandemic (estimated)
  prob3 <- prob1 * prob2     # P(C): unconditional trigger probability
  prob4 <- 1 - prob3         # P(No Trigger)
  
  price3 <- (price1 * prob3) + (price2 * prob4)
  # Total expected bond price under law of total probability
  
  Bond_Price <- append(Bond_Price, price3)  # store for this sigma
  P_C <- append(P_C, prob3)                 # store P(C) for this sigma
}



# ---------------------------
# 6) Build Table 6 format like the paper
# ---------------------------

sigma_target <- seq(0.04, 0.40, 0.04)  # columns used in paper Table 6

idx <- sapply(sigma_target, function(s) which.min(abs(sigma - s)))
# for each target sigma, find closest sigma in your grid (handles floating point)

tab6 <- rbind(
  Bond.Price   = round(Bond_Price[idx], 2),
  Prob.Trigger = round(P_C[idx], 2)
)
# 2-row matrix: bond prices and trigger probabilities

colnames(tab6) <- sprintf("%.2f", sigma_target)  # column names: "0.04", ..., "0.40"

knitr::kable(
  tab6,
  rownames = TRUE,
  col.names = c("sigma_I, sigma_D", sprintf("%.2f", sigma_target)),
  align = c("l", rep("c", ncol(tab6))),
  caption = "Table 6. The bond price movement against volatility terms."
)
# Prints a table with the top-left header cell as "sigma_I, sigma_D"

mean(Bond_Price)
# average of all Bond_Price values across sigma grid (not in the paper table)



# ---------------------------
# 7) Save outputs
# ---------------------------

saveRDS(tab6, file = "table6_like_paper.rds")      # save table as R object
write.csv(tab6, file = "table6_like_paper.csv")    # save table as CSV

